// Proposals Types

/**
 * Proposal generated by an agent
 * @typedef {Object} Proposal
 * @property {string} id - Unique proposal ID
 * @property {string} agent - Agent that generated the proposal
 * @property {string} description - Human-readable description
 * @property {FileChange} change - The file change to apply
 * @property {DiffResult} diff - Computed diff
 * @property {string[]} risks - Potential risks
 */

/**
 * Validation result
 * @typedef {Object} ValidationResult
 * @property {boolean} valid - Whether the proposal is valid
 * @property {string[]} errors - Validation errors
 * @property {string[]} warnings - Validation warnings
 */

export default {};
